if Code.ensure_loaded?(Igniter) do
  defmodule Mix.Tasks.AshFeedback.Install do
    @example "mix igniter.install ash_feedback"
    @shortdoc "Installs ash_feedback into a Phoenix + Ash project"

    @moduledoc """
    Installs `ash_feedback` into a Phoenix + Ash project.

    ## Recommended

        #{@example}

    Igniter adds `ash_feedback` to your deps, fetches it, and runs
    this installer on your codebase. Run `phoenix_replay`'s installer
    first — `ash_feedback`'s installer assumes the
    `:phoenix_replay :storage` key is already present and flips it to
    point at `AshFeedback.Storage`.

    ## What it does

    Phase 1 (current):

      1. Flips the `:phoenix_replay :storage` config from
         `PhoenixReplay.Storage.Ecto` to `{AshFeedback.Storage,
         resource: <HostApp>.Feedback.Entry, repo: <HostApp>.Repo}`.

    Phase 2+ (proposed in `docs/plans/5f-igniter-installer.md`):

      - Generate `<HostApp>.Feedback` domain + register in
        `:ash_domains`
      - Generate concrete `<HostApp>.Feedback.Entry` resource
      - Generate AshStorage `Blob` + `Attachment` + service config
      - Optional `<HostApp>.Feedback.Comment` resource
      - Notice with follow-up commands (`mix ash.codegen`,
        `mix ash.migrate`)

    ## Manual install

    If you've already added `{:ash_feedback, ...}` to your `mix.exs`
    yourself:

        mix ash_feedback.install
    """

    use Igniter.Mix.Task

    @impl Igniter.Mix.Task
    def info(_argv, _composing_task) do
      %Igniter.Mix.Task.Info{
        group: :ash_feedback,
        example: @example,
        schema: [],
        composes: ["phoenix_replay.install", "ash.gen.domain"]
      }
    end

    @impl Igniter.Mix.Task
    def igniter(igniter) do
      igniter
      |> configure_storage()
      |> generate_feedback_domain()
      |> generate_audio_blob_resource()
      |> generate_audio_attachment_resource()
      |> add_resources_to_domain()
      |> configure_audio_storage_service()
      |> Igniter.add_notice("""

      ash_feedback install — Phase 3 complete.

      Next steps (manual until later phases of 5f land):

        See README "Installation" — step 6 onward — for the
        concrete Feedback resource, an optional FeedbackComment,
        and `mix ash.codegen` + `mix ash.migrate`.
      """)
    end

    # --- Storage config patcher ---------------------------------------

    defp configure_storage(igniter) do
      app_name = Igniter.Project.Application.app_name(igniter)
      host = host_module_alias(app_name)
      feedback_resource = Module.concat([host, "Feedback", "Entry"])
      repo = Module.concat([host, "Repo"])

      storage_ast = storage_value_ast(feedback_resource, repo)

      Igniter.Project.Config.configure(
        igniter,
        "config.exs",
        :phoenix_replay,
        [:storage],
        {:code, storage_ast},
        updater: fn zipper ->
          {:ok, Igniter.Code.Common.replace_code(zipper, storage_ast)}
        end
      )
    end

    # Build the `{AshFeedback.Storage, resource: ..., repo: ...}` AST
    # via Sourceror so the rendered output has stable formatting and
    # the host-app module aliases are real `__aliases__` nodes.
    defp storage_value_ast(feedback_resource, repo) do
      Sourceror.parse_string!("""
      {AshFeedback.Storage,
       resource: #{inspect(feedback_resource)},
       repo: #{inspect(repo)}}
      """)
    end

    defp host_module_alias(app_name) do
      app_name
      |> Atom.to_string()
      |> Macro.camelize()
      |> List.wrap()
      |> Module.concat()
    end

    # --- Domain generation patcher ------------------------------------

    # Composes `mix ash.gen.domain` to create `<HostApp>.Feedback` and
    # add it to `:my_app, ash_domains`. `--ignore-if-exists` keeps the
    # patcher idempotent on re-runs.
    defp generate_feedback_domain(igniter) do
      domain = feedback_domain_module(igniter)

      Igniter.compose_task(igniter, "ash.gen.domain", [
        inspect(domain),
        "--ignore-if-exists"
      ])
    end

    # --- Domain resource-list patcher ---------------------------------

    # Adds the resources generated by this installer (Entry, its
    # AshPaperTrail-generated Version companion, Blob, Attachment) to
    # the domain's `resources` block.
    # `Ash.Domain.Igniter.add_resource_reference/3` is idempotent.
    defp add_resources_to_domain(igniter) do
      domain = feedback_domain_module(igniter)

      [
        feedback_entry_module(igniter),
        Module.concat([feedback_entry_module(igniter), "Version"]),
        audio_blob_module(igniter),
        audio_attachment_module(igniter)
      ]
      |> Enum.reduce(igniter, fn resource, acc ->
        Ash.Domain.Igniter.add_resource_reference(acc, domain, resource)
      end)
    end

    # --- AshStorage Blob + Attachment generators ----------------------

    # Generates `<HostApp>.Storage.Blob`, the AshStorage `BlobResource`
    # that backs audio narration uploads. ADR-0001 Question A: hosts
    # own the Blob shape because the storage backend (S3/Disk/MinIO),
    # bucket, and auth strategy are host-specific. We emit a minimal
    # uuid-id Postgres-backed shape that the host can extend with
    # AshOban triggers, custom auth, etc.
    defp generate_audio_blob_resource(igniter) do
      blob = audio_blob_module(igniter)
      domain = feedback_domain_module(igniter)
      repo = host_repo_module(igniter)

      {exists?, igniter} = Igniter.Project.Module.module_exists(igniter, blob)

      if exists? do
        igniter
      else
        Igniter.Project.Module.create_module(igniter, blob, """
        @moduledoc \"\"\"
        AshStorage blob resource backing audio narration uploads on
        feedback rows. Generated by `mix ash_feedback.install`. Host
        owns the shape — extend with AshOban triggers, alternative
        auth, etc., as your app needs.
        \"\"\"
        use Ash.Resource,
          domain: #{inspect(domain)},
          data_layer: AshPostgres.DataLayer,
          extensions: [AshStorage.BlobResource]

        postgres do
          table "blobs"
          repo #{inspect(repo)}
        end

        blob do
        end

        attributes do
          uuid_primary_key :id
        end
        """)
      end
    end

    # Generates `<HostApp>.Storage.Attachment`, the AshStorage
    # `AttachmentResource` that joins blobs to feedback rows via the
    # `:audio_clip` has_one_attached on `<HostApp>.Feedback.Entry`.
    defp generate_audio_attachment_resource(igniter) do
      attachment = audio_attachment_module(igniter)
      blob = audio_blob_module(igniter)
      entry = feedback_entry_module(igniter)
      domain = feedback_domain_module(igniter)
      repo = host_repo_module(igniter)

      {exists?, igniter} = Igniter.Project.Module.module_exists(igniter, attachment)

      if exists? do
        igniter
      else
        Igniter.Project.Module.create_module(igniter, attachment, """
        @moduledoc \"\"\"
        AshStorage attachment resource — joins
        `#{inspect(blob)}` rows to `#{inspect(entry)}` rows via the
        `:audio_clip` has_one_attached declaration emitted by
        `AshFeedback.Resources.Feedback`. Generated by
        `mix ash_feedback.install`.
        \"\"\"
        use Ash.Resource,
          domain: #{inspect(domain)},
          data_layer: AshPostgres.DataLayer,
          extensions: [AshStorage.AttachmentResource]

        postgres do
          table "attachments"
          repo #{inspect(repo)}

          references do
            reference :feedback, on_delete: :delete
          end
        end

        attachment do
          blob_resource #{inspect(blob)}
          belongs_to_resource :feedback, #{inspect(entry)}
        end

        attributes do
          uuid_primary_key :id
        end
        """)
      end
    end

    # --- Storage service config patcher (dev) -------------------------

    # Adds an `AshStorage.Service.Disk` service config under
    # `config :host_app, HostApp.Feedback.Entry` in `dev.exs`. Disk is
    # the right default for `mix ash_feedback.install` — no AWS creds
    # required, no infra to provision; works out of the box on a fresh
    # Phoenix scaffold.
    defp configure_audio_storage_service(igniter) do
      app_name = Igniter.Project.Application.app_name(igniter)
      entry = feedback_entry_module(igniter)

      service_ast =
        Sourceror.parse_string!("""
        [
          service:
            {AshStorage.Service.Disk,
             root: Path.join(File.cwd!(), "tmp/uploads"),
             base_url: "http://localhost:4000",
             direct_upload: true}
        ]
        """)

      Igniter.Project.Config.configure(
        igniter,
        "dev.exs",
        app_name,
        [entry, :storage],
        {:code, service_ast}
      )
    end

    defp feedback_domain_module(igniter) do
      app_name = Igniter.Project.Application.app_name(igniter)
      Module.concat([host_module_alias(app_name), "Feedback"])
    end

    defp feedback_entry_module(igniter) do
      Module.concat([feedback_domain_module(igniter), "Entry"])
    end

    defp audio_blob_module(igniter) do
      app_name = Igniter.Project.Application.app_name(igniter)
      Module.concat([host_module_alias(app_name), "Storage", "Blob"])
    end

    defp audio_attachment_module(igniter) do
      app_name = Igniter.Project.Application.app_name(igniter)
      Module.concat([host_module_alias(app_name), "Storage", "Attachment"])
    end

    defp host_repo_module(igniter) do
      app_name = Igniter.Project.Application.app_name(igniter)
      Module.concat([host_module_alias(app_name), "Repo"])
    end
  end
end
